### PR TITLE
Create gmaps.js fronted for gh-pages

### PR DESCRIPTION
**Pull request by florianschmidt1994**
This will add a fronted for gh-pages which displays all the parking lots using gmaps.js and `$.get()` requests. In the end this will look like the following: 

screen shot 2015-10-27 at 19 09 04

This can hopefully be seen soon as a demo on http://florianschmidt1994.github.io/ParkAPI/, but there still is a known error:

```
XMLHttpRequest cannot load https://park-api.higgsboson.tk/. Origin http://florianschmidt1994.github.io is not allowed by Access-Control-Allow-Origin.
```

Github must be added as an allowed origin in order for this to work properly.

Regards

Florian

### CODE REVIEW

**Comment by florianschmidt1994** [comment]
Regarding the cors stuff: http://flask-cors.readthedocs.org/en/latest/ might be useful, but you guys probably know that already

**Comment by sibbl** [comment]
We should probably not only allow github domains but use the "*" wildcard, shouldn't we?

**Comment by kiliankoe** [comment]
I don't see why not, sounds good!

**Pull request merged**
