### PR TITLE
Hanau

### PR DESCRIPTION
**Pull request by AugustQu**

### CODE REVIEW

**Comment by AugustQu** [comment]
it fails with this message:
`ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%S'`

In the program it converts the date+time via this line:
`        # Letzte Aktualisierung: 04.07.2019 11:03:00
        last_updated = convert_date( parking_data.find('h5').text, 'Letzte Aktualisierung: %d.%m.%Y %H:%M:%S') 
`
The line in the html-file looks like:
`<div class="container-fluid"><h5>Letzte Aktualisierung: 29.07.2019 15:00:00</h5><div >`

On my PC this works well.

Can you please give me a hint.

**Comment by AugustQu** [comment]
after some corrections it now stops with this message:
`  File "/home/travis/build/offenesdresden/ParkAPI/tests/test_cities.py", line 41, in sanity_check
    self.assertTrue(len(city["lots"]) > 0)
AssertionError: False is not true`

It looks like this line causes an exception:
`        last_updated = convert_date( parking_data.find('h5').text, 'Letzte Aktualisierung: %d.%m.%Y %H:%M:%S') 
`

But this works here on my PC.

I will look into this tomorrow.

**Comment by jklmnn** [comment]
The script always returns an empty array of lots:
```json
{
  "last_downloaded": "2019-08-01T19:46:29", 
  "last_updated": "2019-08-01T19:46:29", 
  "lots": []
}
```
This is also the case for the test HTML file. The error is somewhere here:
https://github.com/offenesdresden/ParkAPI/blob/b2e93a29ee368214fb2984e292f0c0ebfded8c2b/park_api/cities/Hanau.py#L23-L32

There is always some exception and the except branch is always executed leading to an empty array. As a suggestion you should catch only specific exceptions, so instead of
```python
try:
  #code
except:
  #code
```
You should write
```python
try:
  #code
except IndexError:
  #code
```
This makes it easier to understand which error you wanted to catch (more clearly: which property lets you decide that the service is not available). Also if you see that the service is not available, it is fine to throw an exception instead of returning empty data. The application will handle that correctly.

I suspect that there's an exception that is thrown in the try block that you didn't intend which causes to trigger the catch block erroneously.

**Comment by AugustQu** [comment]
sorry for beeing late with my reply but I had some other work to do ....

hmmmmmmm

I copied the test-file hanau.html into my environment and even copied the code and: it works like a charm.

Don't know what's going on here.

**Comment by AugustQu** [comment]
here is what I receive in my test-environment:
`{'last_updated': '2019-07-29T13:00:00', 'lots': [{'name': 'Tiefgarage Am Markt', 'free': 70, 'total': 185, 'address': 'Am Markt', 'coords': {'lng': 8.916543, 'lat': 50.132449}, 'state': 'open', 'lot_type': 'Tiefgarage', 'id': 'hanautiefgarageammarkt', 'forecast': False}, 
.............
]}
`

**Comment by jklmnn** [comment]
Since I cannot reproduce the results of your environment (nor do I know what your environment is) I cannot tell anything about the problem.

The relevant environment for us is the Travis CI and the production server. This is a Debian 10 stable with Python 3.7.3 and all dependencies installed via pip into a virtual environment. The backwards compatibility is given to Python 3.5 (Debian 9).

**Comment by AugustQu** [comment]
OK, now the tests passed.

I have added some print-statements which led to another problem. Then I removed them and it works now.

**Pull request closed without merging**
