### PR TITLE
Frankfurt am Main added

### PR DESCRIPTION
**Pull request by stepan-romankov**
Please add Frankfurt am Main scraper

### CODE REVIEW

**Comment by stepan-romankov** [comment]
Please include my pull request!

**Comment by stepan-romankov** [comment]
This was done on Open Data Day in the OK Lab Frankfurt. We'd like to integrate Frankfurt int to the app and would be interested in the machine learning part also.

If you have any further questions, contact @aCandidMind on GitHub or @a_candid_mind on the OKFN Slack of Germany. If there is something wrong with the pull request contact me.

**Comment by jklmnn** [comment]
Btw since Frankfurt seems to have an API, should we set `active_support` to `true`?

**Comment by stepan-romankov** [comment]
I suggest yes :)

**Comment by jklmnn** [comment]
@stepan-romankov you have no attribution set. Is this correct or should we add that?

**Comment by stepan-romankov** [comment]
@jklmnn could you please add, cause I'm not sure what is it :)

**Comment by jklmnn** [comment]
It's an API field for the contributor, it contains the contributor, a license and an url to the contributor. Example for Freiburg:

    "attribution": {
        "contributor": "Stadt Freiburg",
        "license": "dl-de/by-2-0",
        "url": "http://www.freiburg.de/pb/,Lde/231355.html"
    },

You can just tell me the fields and I'll add it.

**Comment by stepan-romankov** [comment]
"attribution":{
            "contributor":"Stadt Frankfurt am Main",
            "url":"http://daten.frankfurt.de/organization/strassenverkehrsamt",
            "license":"dl-de/by-2-0"
          }

Not sure if contributor is who provides data or me...

**Comment by stepan-romankov** [comment]
@jklmnn I've checked,  license is correct "dl-de/by-2-0"

**Comment by jklmnn** [comment]
Looks fine, I'll merge it.
@stepan-romankov in this case its the contributor who provides the data, so Stadt Frankfurt am Main is fine.

**Comment by aCandidMind** [comment]
Nice work @stepan-romankov. Thanks for the pull request. You served Frankfurt well.

**Pull request merged**
