### PR TITLE
Please add Erfurt to the ParkAPI

### PR DESCRIPTION
**Pull request by jurkov**
Dear devs at offenesdresden,

please add my tiny script to get the parking lots of erfurt.
I didn't check the all, coz i had no time to setup the whole project.

best regards,
Christoph J.

### CODE REVIEW

**Comment by kiliankoe** [comment]
Awesomesauce! 

@Mic92 since you're currently more familiar with the code, can you have a quick look if this looks right? Looks fine from my point (only thing is the state, which should be `unknown` instead of `nodata`).

**Comment by kiliankoe** [comment]
I just tried getting this to work locally and am puzzled by Erfurt's page. Is all the data really listed there on parseable? I have a feeling one would actually have to select the single lots with something a little more powerful than bs4. Odd page...

**Comment by jurkov** [comment]
This is hightec from Erfurt! Please enjoy!

**Comment by jklmnn** [comment]
I looked through the code and made a few fixes, we might merge this to a new branch, apply the fixes and then merge it into master.

**Comment by jurkov** [comment]
i applied the fixes, travis don't like it and i also can't merge it (no write access?)

**Comment by jklmnn** [comment]
I can't help you with travis. Maybe @kiliankoe or @Mic92 ?

**Comment by kiliankoe** [comment]
Travis is failing on setting up the DB, I think it's safe to ignore that for now. If the tests run locally everything is awesome!

**Comment by Mic92** [comment]
database related part in travis should be fixed by now.

**Comment by jurkov** [comment]
What can i do to speed up the merge?

**Comment by Mic92** [comment]
Add a testfile to https://github.com/offenesdresden/ParkAPI/tree/master/tests/fixtures
and 3 lines of test code to: https://github.com/offenesdresden/ParkAPI/blob/master/tests/test_cities.py

**Comment by kiliankoe** [comment]
I feel kinda bad that this still isn't merged yet. Unfortunately I've also lost track somewhat 😕 Anybody clear on the current state of this PR?

**Comment by jklmnn** [comment]
I would not merge this. The original link gives an 302 back and refers to http://geoportal.erfurt.de/gis/externalcall.jsp?project=1&amp;client=auto&amp;client_app_referer=asp which seems to give a new webapp. So the scraper isn't working at all anymore.

**Comment by jurkov** [comment]
Hey, the local city it department updated the gis system some days ago. You can still find the parking lot data inside the gis system. At the moment i have no idea and no time to build a new grawler.

**Comment by jklmnn** [comment]
I didn't find something. Can you point me to  the data? Maybe I'll write something if I find time.

**Comment by jurkov** [comment]
http://geoportal.erfurt.de/gis/externalcall.jsp?project=4&language=de&client=core&x=642939.2330031326&y=5648746.332509715&scale=3500&view=parken

**Pull request closed without merging**
