### PR TITLE
Add "Parkhaus Kunstmuseum" to Basel

### PR DESCRIPTION
**Pull request by jb3-2**

### CODE REVIEW

**Comment by defgsus** [comment]
Hello @jb3-2 
thank you for these fixes.

(I'm not a maintainer in this repo, just want to express my gratitude ;-)

**Review by jklmnn — APPROVED** [review]

**Comment by jb3-2** [comment]
@jklmnn Thanks for merging! The number of free parking lots of this new Parkhaus is now visible on the API, but total lots, coordinates and address are still missing, see https://api.parkendd.de/Basel (last line). Can I somehow help fixing this?

**Comment by jklmnn** [comment]
@jb3-2 I forgot to update the server. The ParkAPI already finds the new data but the meta data is not yet on the server. I will fix this.

**Comment by jklmnn** [comment]
It is fixed now.

**Comment by jb3-2** [comment]
Thanks!! <3

**Pull request closed without merging**
