### PR TITLE
[WIP] Restructure

### PR DESCRIPTION
**Pull request by kiliankoe**
This is still very much a work in progress without a lot of progress. I spent some time in the last few days rethinking the basic db (and app) structure. Not sure how far I'll get in the next few days, so I'm dumping this here for now. 

Basic ideas:
- The old database schema is based on my laziness and uses PostgreSQL like a nosql database, which is super weird and has lots of issues, this amends that.
- The old scraper and server are much too intertwined and could use some splitting apart, maybe even throwing away the entire server in the process and replacing it with something more sensible.
- The API responses are weirdly structured and should be optimized, the old format will obviously still have to be supported indefinitely for the apps.
- The city data and modules should leave this repository (@jklmnn already did that) and data should be updated regularly. The geojson files are already out-of-date and contain wildly inconsistent data.
- Deployment should be optimized, ideally through the use of a Docker image/compose file, see #103. 

This PR will likely stay open for a while, please unsubscribe if you don't want to get GitHub notifications for every update 🙈 I apologize in advance! 😅 I'm opening it instead of just leaving a branch so that changes can be discussed here.

### CODE REVIEW

**Comment by kiliankoe** [comment]
The biggest change for now is the proposed db structure. It can be found here:

https://github.com/offenesdresden/ParkAPI/blob/ad3a86a7db021bdc3d58eedf71612f4e80187d56/db/parkapi_schema.sql#L1-L84

There's (at least) two todos there still open. Updating the `created_at` and `updated_at` fields with a trigger on the respective tables and automatically creating pools (see #130) for every source.

**Comment by jklmnn** [comment]
I just want to state that I did not yet remove the modules from the main repo completely. There are still unresolved dependencies. You can use the modules from https://github.com/offenesdresden/ParkApi_Modules with my ParkAPI fork https://github.com/offenesdresden/ParkAPI/tree/external_modules but you cannot use the modules alone as they still require dependencies only available in the ParkAPI repo. This is surely something that needs to be fixed.

**Comment by kiliankoe** [comment]
relationships real large

Dumping this here so that I don't lose it. Forecast data is still missing.

**Comment by kiliankoe** [comment]
Closing in favor of a new approach.

**Pull request closed without merging**
